######################################################################
# Automatically generated by qmake (2.01a) Tue 7. Jun 21:32:09 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += glicko.h player.h player_display.h
SOURCES += glicko.cpp main.cpp player.cpp player_display.cpp
